apiVersion: v1
kind: Deployment
metadata: 
  name: myapp-blue
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
        - name: myapp
          image: us-central1-docker.pkg.dev/REPLACE_GCP_PROJECT/blue-green-repo/myapp:REPLACE_TAG
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "blue"
            - name: VERSION
              value: "REPLACE_TAG"
          readinessProbe:
            httpGet: 
              path: /readyz 
              port: 8080 
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080 
            initialDelaySeconds: 2
            periodSeconds: 10

